---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: redis-haproxy
  labels:
    run: redis-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis-haproxy
  template:
    metadata:
      creationTimestamp: 
      labels:
        run: redis-haproxy
    spec:
      containers:
      - name: redis-haproxy
        image: garylai/k8s-redis-haproxy:latest
        ports:
        - containerPort: 6379
          hostIP: 0.0.0.0
        args:
        - '3'
      restartPolicy: Always
