---
kind: Service
apiVersion: v1
metadata:
  name: redis
  labels:
    run: redis
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    run: redis
  clusterIP: None
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: redis
  labels:
    run: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      creationTimestamp: 
      labels:
        run: redis
    spec:
      containers:
      - name: redis
        image: garylai/k8s-redis:latest
        ports:
        - containerPort: 6379
          hostIP: 0.0.0.0
        volumeMounts:
        - name: data-volume
          mountPath: "/data"
        args:
        - redis
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
